
sample_count = 16

[camera]
type = "pinhole"
fov = 34.0
width = 256
height = 256

orig = [2,3,5]
up = [0,1,0]
target = [0,0,0]


[integrator]
type = "base"

[sampler]
type = "pcg_random"

[[emitters]]
type = "area"
radiance = [1,1,1]

[emitters.shape]
type = "sphere"
center = [-5,-5,-7]
radius = 5.0


[[shapes]]
type = "sphere"
center = [0,0,-10]
radius = 1.0
[shapes.bsdf]
type = "diffuse"
basecolor = [1,1,0]

[[shapes]]
type = "sphere"
center = [2,2,-10]
radius = 0.5

[shapes.bsdf]
type = "diffuse"
basecolor = [1,1,1]