
sample_count = 1024

[camera]
type = "pinhole"
fov = 34.2
width = 256
height = 256

[integrator]
type = "base"

[sampler]
type = "independent"

[[emitters]]
type = "area"
radiance = [1,1,1]

[emitters.shape]
type = "sphere"
center = [-1,-1,-7]
radius = 0.5


[[shapes]]
type = "sphere"
center = [0,0,-10]
radius = 2.0
[shapes.bsdf]
type = "diffuse"
basecolor = [1,1,1]

#[[shapes]]
#type = "sphere"
#center = [2,2,-10]
#radius = 0.5
#
#[shapes.bsdf]
#type = "diffuse"
#basecolor = [1,1,1]